version: 2
updates:
  # .NET NuGet Dependencies
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "knowthankyew"
    groups:
      dotnet-dependencies:
        patterns:
          - "*"

  # Node / Playwright Dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "knowthankyew"
    groups:
      npm-dependencies:
        patterns:
          - "*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "knowthankyew"
    groups:
      github-actions:
        patterns:
          - "*"
